name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    strategy:
      matrix:
        os:
          - macOS-latest
        raku-version:
          - 'latest'
          - '2021.10'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Install Libraries (MacOS)
        run: |
          brew reinstall fontconfig
      - name: Install Dependencies
        run: |
          zef install --/test LibraryMake
          zef install --deps-only .
          raku Build.pm6 -I /opt/homebrew/opt/fontconfig/include -L /opt/homebrew/opt/fontconfig/lib
      - name: Run Tests
        run: |
          export LD_LIBRARY_PATH=/opt/homebrew/opt/fontconfig/lib
          zef install .
